// File generated by FlutterFire CLI.
// Run `flutterfire configure` to generate the correct values for your project.
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform.
///
/// IMPORTANT: This is a placeholder file. To use Firebase features:
/// 1. Install the FlutterFire CLI: `dart pub global activate flutterfire_cli`
/// 2. Run: `flutterfire configure`
/// 3. This will generate the correct values for your Firebase project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to fix this.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase configuration
  // Run `flutterfire configure` to generate the correct values

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAww1-6WnQVwe2ZauRNr9YYweX5H4c0i6c',
    appId: '1:909667897523:web:be7768f078d422650560c6',
    messagingSenderId: '909667897523',
    projectId: 'tigerhunt-ad97a',
    authDomain: 'tigerhunt-ad97a.firebaseapp.com',
    storageBucket: 'tigerhunt-ad97a.firebasestorage.app',
    measurementId: 'G-NNZQPBPH5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5IbJ1R_99SWNn1o_ZmX0fAvvn0ptgq0',
    appId: '1:909667897523:android:887f804bca22dd370560c6',
    messagingSenderId: '909667897523',
    projectId: 'tigerhunt-ad97a',
    storageBucket: 'tigerhunt-ad97a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeYHrR7LUPFPQKKEZXrVBj1GHwvnMt-W4',
    appId: '1:909667897523:ios:f49d5bbdd965e26a0560c6',
    messagingSenderId: '909667897523',
    projectId: 'tigerhunt-ad97a',
    storageBucket: 'tigerhunt-ad97a.firebasestorage.app',
    iosBundleId: 'com.tigerhunt.tigerhunt',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeYHrR7LUPFPQKKEZXrVBj1GHwvnMt-W4',
    appId: '1:909667897523:ios:f49d5bbdd965e26a0560c6',
    messagingSenderId: '909667897523',
    projectId: 'tigerhunt-ad97a',
    storageBucket: 'tigerhunt-ad97a.firebasestorage.app',
    iosBundleId: 'com.tigerhunt.tigerhunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAww1-6WnQVwe2ZauRNr9YYweX5H4c0i6c',
    appId: '1:909667897523:web:444f348eca77cba70560c6',
    messagingSenderId: '909667897523',
    projectId: 'tigerhunt-ad97a',
    authDomain: 'tigerhunt-ad97a.firebaseapp.com',
    storageBucket: 'tigerhunt-ad97a.firebasestorage.app',
    measurementId: 'G-0EPRL9451Z',
  );
}
